// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOEO6mMrl33BJ8yzZbpWVKFJQ9KKC3Ekc',
    appId: '1:1013450239421:web:fcae3a0cf1c4fa2f5e36d4',
    messagingSenderId: '1013450239421',
    projectId: 'bazar-d3b0f',
    authDomain: 'bazar-d3b0f.firebaseapp.com',
    storageBucket: 'bazar-d3b0f.appspot.com',
    measurementId: 'G-90Y7J3KXB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRH9JNVruJcgYM2mhH4uDEzI9l7mOEil8',
    appId: '1:1013450239421:android:e1343421999564965e36d4',
    messagingSenderId: '1013450239421',
    projectId: 'bazar-d3b0f',
    storageBucket: 'bazar-d3b0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdHIVN49np8RmQ6BG6zIvEr9I3jEw8fg',
    appId: '1:1013450239421:ios:8be8926fab1206875e36d4',
    messagingSenderId: '1013450239421',
    projectId: 'bazar-d3b0f',
    storageBucket: 'bazar-d3b0f.appspot.com',
    iosBundleId: 'com.example.bazarApp',
  );
}
