name: bazar_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.1
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  riverpod: ^2.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/shopping-store.png"

flutter:
  assets:
    - assets/
  uses-material-design: true
